source "https://rubygems.org"

gem "redis", "~> 5.0"
gem "pg", "~> 1.5"
gem "octokit", "~> 8.0"
gem "dotenv", "~> 3.0"
gem "json"

group :test do
  gem "minitest", "~> 5.0"
  gem "mocha", "~> 2.0"
  gem "rake", "~> 13.0"
end
